name: 🚀 Gitea App DevSecOps CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read

jobs:
  build-scan-and-deploy:
    name: 🛡️ Build, Security Scan & GitOps Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Application Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔐 Authenticate to AWS via OIDC (No Static Keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_IAM_ROLE}}
          aws-region: ap-south-1
  
